# -*- coding: utf-8 -*-
import math
TICKS_PER_SEC = 60

SECTOR_SIZE = 16

WALKING_SPEED = 5
FLYING_SPEED = 15

GRAVITY = 20.0
MAX_JUMP_HEIGHT = 1.0
JUMP_SPEED = math.sqrt(2 * GRAVITY * MAX_JUMP_HEIGHT)
MAX_VELOCITY = 50

PLAYER_HEIGHT = 2
WORLD_SIZE = 80
MAX_DRAW_LENGTH = 8
